#!/bin/bash

#GO INTO DJANGO DIRECTORY
cd RUMEN/

#INSTALL AND RUN PIPENV
pip3 install pipenv
pipenv install --system --deploy

#CONFIGURE THE DATA BASE
python3 manage.py migrate

#INSTALL REACT'S PACKAGES AND BUILD THE GUI
cd frontend
npm i
npm run build
