#!/bin/bash

#GO INTO DJANGO DIRECTORY
cd RUMEN/

#INSTALL AND RUN PIPENV
pip3 install pipenv
pipenv shell
pipenv sync

#INSTALL REACT'S PACKAGES AND BUILD THE GUI
cd frontend
npm i
npm run build

#CONFIGURE THE DATA BASE
cd ..
python3 manage.py migrate
