# Generated by Django 4.0.2 on 2022-02-28 08:30

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChessBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=api.models.codeGenerator, max_length=36, unique=True)),
                ('host', models.CharField(default='', max_length=64, unique=True)),
                ('board', models.CharField(default='bRbNbBbQbKbBbNbR/bPbPbPbPbPbPbPbP/8/8/8/8/wPwPwPwPwPwPwPwP/wRwNwBwQwKwBwNwR', max_length=128)),
                ('personToMove', models.CharField(default='white', max_length=8)),
            ],
        ),
    ]
